### ISSUE TITLE
could not read protos repository

### ISSUE THREAD

**Issue by sawalon** [SwiftcordApp/DiscordKit#16]
![Screen Shot 2022-10-15 at 22 11 02](https://user-images.githubusercontent.com/97076253/195991031-22e919e1-051b-4306-a7da-643bc834206e.png)
Thanks for you great work!
Couldn't update repository submodules in Swiftcord proj
just forget make git@github.com:SwiftcordApp/protos.git public?

**Comment by cryptoAlgorithm** [comment]
@sawalon This is actually no accident, the compiled protos are kept separate and private because they're completely reverse engineered which is against Discord's ToS. I'm working on an action to compile them into XCFrameworks so DiscordKit can be built without access to the private repo, very sorry. If you'd like, I can give you access to the source on a case by case bases.

**Comment by cryptoAlgorithm** [comment]
If you're interested, you can drop me a message on Discord or in the Swiftcord server

**Comment by sawalon** [comment]
> @sawalon Now, I've added the compiled proto files directly to DiscordKit! You'll no longer have this issue, happy coding!

thank you very much bro

**Comment by cryptoAlgorithm** [comment]
Not a problem 😊
